import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { 
  argbFromHex, 
  themeFromSourceColor,
  hexFromArgb 
} from '@material/material-color-utilities';

const SCHEMES: Record<string, string> = {
  default: '#6750A4',
  teal: '#006A6A',
  blue: '#0061A4',
  green: '#386A20',
  orange: '#A03D00',
  pink: '#984061',
};

function toKebabCase(str: string): string {
  return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

function buildThemes(): void {
  let css = '/* AUTO-GENERATED by scripts/build-themes.ts - DO NOT EDIT */\n\n';
  
  for (const [name, seed] of Object.entries(SCHEMES)) {
    const theme = themeFromSourceColor(argbFromHex(seed));
    
    const light = theme.schemes.light.toJSON();
    const dark = theme.schemes.dark.toJSON();
    
    if (name === 'default') {
      css += `/* Default scheme (based on ${seed}) */\n`;
    } else {
      css += `\n/* ${name.charAt(0).toUpperCase() + name.slice(1)} Color Scheme (based on ${seed}) */\n`;
    }
    
    const schemeSelector = name === 'default' ? '' : `[data-scheme="${name}"]`;
    
    if (schemeSelector) {
      css += `${schemeSelector} {\n`;
    } else {
      css += `:root, [data-theme="light"] {\n`;
    }
    
    for (const [key, argb] of Object.entries(light)) {
      const cssVar = `--md-sys-color-${toKebabCase(key)}`;
      css += `  ${cssVar}: ${hexFromArgb(argb as number)};\n`;
    }
    css += `}\n`;
    
    if (schemeSelector) {
      css += `\n[data-theme="dark"]${schemeSelector} {\n`;
    } else {
      css += `\n[data-theme="dark"] {\n`;
    }
    
    for (const [key, argb] of Object.entries(dark)) {
      const cssVar = `--md-sys-color-${toKebabCase(key)}`;
      css += `  ${cssVar}: ${hexFromArgb(argb as number)};\n`;
    }
    css += `}\n`;
  }

  css += `
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
`;
  
  const defaultDark = themeFromSourceColor(argbFromHex(SCHEMES.default)).schemes.dark.toJSON();
  for (const [key, argb] of Object.entries(defaultDark)) {
    const cssVar = `--md-sys-color-${toKebabCase(key)}`;
    css += `    ${cssVar}: ${hexFromArgb(argb as number)};\n`;
  }
  
  css += `  }
}
`;
  
  const tokensDir = 'src/styles/tokens';
  if (!existsSync(tokensDir)) {
    mkdirSync(tokensDir, { recursive: true });
  }
  
  writeFileSync(`${tokensDir}/schemes.css`, css);
  console.log(`✓ Generated ${tokensDir}/schemes.css`);
}

buildThemes();
